name: Continuous Integration

on:
  push:

jobs:
  lint-format-and-type-check:
    name: Lint Format and Type Check
    runs-on: ubuntu-latest

    permissions:
      contents: read
      deployments: write

    strategy:
      matrix:
        node-version: ["18"]

    steps:
      - uses: actions/checkout@v3
      - uses: volta-cli/action@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install
        run: npm ci .

      - name: Lint
        run: npm run lint

      - name: Format
        run: npm run format

      - name: Type Check
        run: npm run check-types
